### ISSUE TITLE
Security: update package use of js-yaml library

### ISSUE THREAD

**Issue by camsjams** [viglucci/simple-knex-fixtures#1]
There are a few advisories for the npm package [js-yaml](https://www.npmjs.com/package/js-yaml) that can be solved by upgrading to the latest version (currently at v3.13.1).

By upgrading, these issues should be fixed:
## Code Injection
- [advisory 788](https://www.npmjs.com/advisories/788)
- [SNYK-JS-JSYAML-173999](https://snyk.io/vuln/SNYK-JS-JSYAML-173999)

Fixed in [PR js-yaml 475](https://github.com/nodeca/js-yaml/pull/475)

## Denial of Service
- [advisory 813](https://www.npmjs.com/advisories/813)
- [SNYK-JS-JSYAML-174129](https://snyk.io/vuln/SNYK-JS-JSYAML-174129)

Fixed in [PR js-yaml 480](https://github.com/nodeca/js-yaml/pull/480)

## Regular Expression Denial of Service
Additionally, `js-yaml` has a downstream issue via `js-yaml > argparse > underscore.string` [advisory 745](https://www.npmjs.com/advisories/745) which should also be fixed with the package bump.

**Comment by viglucci** [comment]
Thanks for the PR @camsjams! I'll review this soon.

**Comment by camsjams** [comment]
Thanks for merging!
